name: seltzer
version: 0.2.3-alpha
description: An elegant and rich cross-platform HTTP library for Dart.
authors:
  - Matan Lurey <matanl@google.com>
  - Kendal Harland <kjharland@google.com>
homepage: https://github.com/matanlurey/seltzer
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  meta: "^1.0.4"
  quiver: "^0.23.0"
dev_dependencies:
  dart_style: ">=0.2.10"
  test: ">=0.12.15"
